[package]
name = "hello_world_cargo"
version = "0.1.1"
authors = ["juanitodread <juanitodread@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
